import React from "react"

const FAQSection = () => {
  const faqs = [
    {
      question: "Is it legal to generate random SSN numbers?",
      answer:
        "Yes, generating random SSN numbers for testing and development purposes is legal when the numbers are clearly fake and used only for software testing, educational research, or development activities. Our generator creates numbers that follow the correct format but do not correspond to real individuals, making them safe for testing purposes.",
    },
    {
      question: "How do random SSN generators work?",
      answer:
        "Random SSN generators create nine-digit numbers in the XXX-XX-XXXX format following Social Security Administration format rules. Our generator avoids forbidden area numbers (000, 666, 900-999), ensures group numbers are not 00, and serial numbers are not 0000, while randomly generating valid combinations that don't match real SSNs.",
    },
    {
      question: "What is the difference between fake and real SSN numbers?",
      answer:
        "Fake SSN numbers generated by our tool follow the correct format and validation rules but are randomly created to avoid matching any real person's Social Security Number. They're designed specifically for testing and development purposes, while real SSNs are issued by the Social Security Administration to actual individuals.",
    },
    {
      question: "Can I use generated SSNs for software testing?",
      answer:
        "Absolutely! Generated SSNs are perfect for software testing, QA processes, database development, form validation testing, and educational purposes. They provide realistic test data that follows proper formatting rules without using real personal information, ensuring compliance with privacy and security best practices.",
    },
    {
      question: "What SSN formats and validation rules does this tool follow?",
      answer:
        "Our generator follows official SSN formatting rules: XXX-XX-XXXX format, avoids area numbers 000 and 666, excludes the 900-999 range reserved for future use, ensures group numbers are 01-99 (not 00), and serial numbers are 0001-9999 (not 0000). All generated numbers pass standard SSN validation algorithms.",
    },
    {
      question: "Is this random SSN generator free to use?",
      answer:
        "Yes! This SSN generator is completely free and doesn't require any registration or app download. It works directly in your browser on any device including iPhone, iPad, Android, and desktop computers. Generate unlimited SSN numbers for testing and educational purposes without any restrictions.",
    },
    {
      question: "What export formats are available for batch generation?",
      answer:
        "Our tool supports multiple export formats for batch SSN generation: Plain text (.txt) for simple lists, CSV (.csv) for spreadsheet compatibility with optional metadata columns, and JSON (.json) for programming and API integration with structured data including validation information.",
    },
    {
      question: "How do I validate SSN numbers in my application?",
      answer:
        "To validate SSN numbers, check for exactly 9 digits, verify the XXX-XX-XXXX format, ensure area number is not 000, 666, or 900-999, confirm group number is not 00, and verify serial number is not 0000. Our tool includes validation examples and educational content about implementing proper SSN validation in your code.",
    },
    {
      question: "Are the generated SSN numbers truly random?",
      answer:
        "Yes, our generator uses cryptographically secure random number generation within the constraints of valid SSN formatting rules. Each generated number is independently random and statistically unlikely to be duplicated, even across large batch generations, while maintaining compliance with SSN format standards.",
    },
    {
      question: "Can I contribute to or customize this SSN generator?",
      answer:
        "This tool is part of our open-source developer toolkit. You can find the source code on our GitHub repository where you can suggest improvements, report issues, or contribute new features. The generator is designed to be educational and transparent about how SSN validation and generation works.",
    },
  ]

  return (
    <section className="mt-20 rounded-xl bg-slate-800 p-8">
      <h2 className="mb-6 text-2xl font-bold text-white">
        Frequently Asked Questions About SSN Generation
      </h2>
      <div className="space-y-6">
        {faqs.map((faq, index) => (
          <div key={index} className="border-b border-slate-700 pb-4 last:border-b-0">
            <h3 className="mb-2 text-lg font-semibold text-white">{faq.question}</h3>
            <p className="leading-relaxed text-slate-400">{faq.answer}</p>
          </div>
        ))}
      </div>
    </section>
  )
}

export default FAQSection
