"use client"

import React, { useEffect } from "react"
import { OutputFormat, type TableData } from "../types"
import { renderHTMLTable, renderASCIITable, renderJSON } from "../lib/table-generator"

interface TableResultModalProps {
  isOpen: boolean
  onClose: () => void
  tableData: TableData | null
  format: OutputFormat
  loading?: boolean
  error?: string
}

export default function TableResultModal({
  isOpen,
  onClose,
  tableData,
  format,
  loading = false,
  error,
}: TableResultModalProps) {
  const [copied, setCopied] = React.useState(false)
  // Close modal with ESC key
  useEffect(() => {
    const handleEscape = (e: KeyboardEvent) => {
      if (e.key === "Escape") {
        onClose()
      }
    }

    if (isOpen) {
      document.addEventListener("keydown", handleEscape)
      document.body.style.overflow = "hidden" // Prevent background scrolling
    }

    return () => {
      document.removeEventListener("keydown", handleEscape)
      document.body.style.overflow = "unset"
    }
  }, [isOpen, onClose])

  if (!isOpen) return null

  // Pre-calculate rendered content for button usage
  const renderedContent = (() => {
    if (!tableData) return ""
    switch (format) {
      case OutputFormat.HTML:
        return renderHTMLTable(tableData)
      case OutputFormat.ASCII:
        return renderASCIITable(tableData)
      case OutputFormat.JSON:
        return renderJSON(tableData)
      default:
        return renderHTMLTable(tableData)
    }
  })()

  const copyToClipboard = async (text: string) => {
    try {
      // Add website promotion information to copied content
      const promotionText = `

──────────────────────────────────────────────────
📊 Generated by JSON to Table Converter
🚀 Powered by GeeksKai - https://geekskai.com

Discover more amazing developer tools:
✨ Free Tools  🛠️ Utilities  📚 Resources
──────────────────────────────────────────────────`

      const textWithPromotion = text + promotionText
      await navigator.clipboard.writeText(textWithPromotion)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch (err) {
      console.error("Failed to copy:", err)
    }
  }

  const downloadAsFile = (content: string, filename: string) => {
    // Add website promotion information to downloaded content
    const promotionText =
      format === OutputFormat.JSON
        ? "" // JSON format already has promotion info added in renderJSON
        : `

──────────────────────────────────────────────────
📊 Generated by JSON to Table Converter
🚀 Powered by GeeksKai - https://geekskai.com

Discover more amazing developer tools:
✨ Free Tools  🛠️ Utilities  📚 Resources

Visit geekskai.com for more awesome tools!
──────────────────────────────────────────────────`

    const contentWithPromotion = content + promotionText
    const blob = new Blob([contentWithPromotion], { type: "text/plain" })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = filename
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  const getFileExtension = (format: OutputFormat): string => {
    switch (format) {
      case OutputFormat.HTML:
        return "html"
      case OutputFormat.ASCII:
        return "txt"
      case OutputFormat.JSON:
        return "json"
      default:
        return "txt"
    }
  }

  const renderContent = () => {
    if (loading) {
      return (
        <div className="flex h-96 items-center justify-center">
          <div className="flex items-center gap-4">
            <div className="h-8 w-8 animate-spin rounded-full border-4 border-orange-500/30 border-t-orange-500"></div>
            <span className="text-lg text-white">Processing data...</span>
          </div>
        </div>
      )
    }

    if (error) {
      return (
        <div className="rounded-2xl border border-red-500/30 bg-red-500/10 p-8 text-center">
          <div className="mb-4 text-6xl">❌</div>
          <h3 className="mb-2 text-xl font-semibold text-red-400">Processing Error</h3>
          <p className="text-red-300">{error}</p>
        </div>
      )
    }

    if (!tableData) {
      return (
        <div className="flex h-96 items-center justify-center text-center">
          <div className="space-y-4">
            <div className="text-6xl">📊</div>
            <div>
              <h3 className="text-xl font-semibold text-white">No Data Yet</h3>
              <p className="text-slate-300">Select a data source to generate a table</p>
            </div>
          </div>
        </div>
      )
    }

    return (
      <div className="space-y-6">
        {/* Metadata information tags - Enhanced visual distinction */}
        <div className="rounded-2xl border border-orange-500/20 bg-gradient-to-r from-orange-500/5 to-red-500/5 p-4 backdrop-blur-sm">
          <div className="flex flex-wrap gap-3 text-sm">
            <div className="inline-flex items-center gap-2 rounded-lg border border-orange-500/30 bg-orange-500/15 px-3 py-2">
              <span className="text-orange-400">📊</span>
              <span className="font-medium text-orange-300">
                {tableData.metadata.totalRows} rows × {tableData.metadata.totalColumns} columns
              </span>
            </div>
            <div className="inline-flex items-center gap-2 rounded-lg border border-purple-500/30 bg-purple-500/15 px-3 py-2">
              <span className="text-purple-400">📋</span>
              <span className="font-medium text-purple-300">
                Type: {tableData.metadata.dataType}
              </span>
            </div>
            <div className="inline-flex items-center gap-2 rounded-lg border border-blue-500/30 bg-blue-500/15 px-3 py-2">
              <span className="text-blue-400">🎨</span>
              <span className="font-medium text-blue-300">Format: {format}</span>
            </div>
          </div>
        </div>

        {/* Content display area */}
        <div className="scrollbar-thin scrollbar-track-slate-800/50 scrollbar-thumb-orange-500/60 hover:scrollbar-thumb-orange-500/80 to-red-500/3 relative max-h-[60vh] overflow-auto rounded-2xl border border-orange-500/30 bg-gradient-to-br from-orange-500/5 p-6 backdrop-blur-sm">
          {format === OutputFormat.HTML ? (
            <div dangerouslySetInnerHTML={{ __html: renderedContent }} />
          ) : (
            <pre className="whitespace-pre-wrap text-sm text-white">{renderedContent}</pre>
          )}
        </div>
      </div>
    )
  }

  return (
    <>
      {/* Background overlay */}
      <div
        className="fixed inset-0 z-50 bg-black/60 backdrop-blur-sm transition-opacity duration-300"
        onClick={onClose}
      />

      {/* Modal content */}
      <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
        <div
          className="animate-in fade-in-0 zoom-in-95 relative max-h-[90vh] w-full max-w-6xl overflow-hidden rounded-3xl border border-white/10 bg-gradient-to-br from-orange-500/25 via-red-500/20 to-pink-500/25 shadow-2xl backdrop-blur-xl duration-300"
          onClick={(e) => e.stopPropagation()}
        >
          {/* Decorative background elements */}
          <div className="absolute -right-16 -top-16 h-36 w-36 rounded-full bg-gradient-to-br from-orange-500/15 to-red-500/15 blur-3xl"></div>
          <div className="absolute -bottom-16 -left-16 h-32 w-32 rounded-full bg-gradient-to-br from-red-500/15 to-pink-500/15 blur-3xl"></div>

          <div className="relative p-8">
            {/* Title bar */}
            <div className="mb-8 flex items-center justify-between">
              <div className="inline-flex items-center gap-3 rounded-full border border-orange-500/30 bg-gradient-to-r from-orange-500/10 to-red-500/10 px-6 py-3 backdrop-blur-sm">
                <span className="text-2xl">📋</span>
                <h2 className="bg-gradient-to-r from-orange-400 via-red-400 to-pink-400 bg-clip-text text-2xl font-bold text-transparent">
                  Generated Table
                </h2>
              </div>

              {/* Top-right action button group */}
              <div className="flex items-center gap-3">
                {/* Copy to Clipboard button */}
                {!loading && !error && tableData && (
                  <button
                    onClick={() => copyToClipboard(renderedContent)}
                    className={`group relative overflow-hidden rounded-xl border px-4 py-2 transition-all duration-300 hover:shadow-lg ${
                      copied
                        ? "border-emerald-500/50 bg-emerald-500/20 text-emerald-300 hover:shadow-emerald-500/25"
                        : "border-green-500/40 bg-green-500/15 text-green-300 hover:border-green-400/60 hover:shadow-green-500/25"
                    }`}
                    title="Copy table to clipboard"
                  >
                    <div className="absolute inset-0 bg-gradient-to-br from-green-500/10 opacity-0 transition-opacity duration-300 group-hover:opacity-100"></div>
                    <span className="relative flex items-center gap-2 text-sm font-medium">
                      <span className="text-base">{copied ? "✅" : "📋"}</span>
                      {copied ? "Copied!" : "Copy"}
                    </span>
                  </button>
                )}

                {/* Download File button */}
                {!loading && !error && tableData && (
                  <button
                    onClick={() =>
                      downloadAsFile(renderedContent, `table.${getFileExtension(format)}`)
                    }
                    className="group relative overflow-hidden rounded-xl border border-blue-500/40 bg-blue-500/15 px-4 py-2 text-blue-300 transition-all duration-300 hover:border-blue-400/60 hover:shadow-lg hover:shadow-blue-500/25"
                    title="Download table as file"
                  >
                    <div className="absolute inset-0 bg-gradient-to-br from-blue-500/10 opacity-0 transition-opacity duration-300 group-hover:opacity-100"></div>
                    <span className="relative flex items-center gap-2 text-sm font-medium">
                      <span className="text-base">💾</span>
                      Download
                    </span>
                  </button>
                )}

                {/* Close button */}
                <button
                  onClick={onClose}
                  className="group relative overflow-hidden rounded-xl border border-slate-500/30 bg-slate-500/10 p-3 text-slate-300 transition-all duration-300 hover:bg-slate-500/20 hover:shadow-lg hover:shadow-slate-500/25"
                  title="Close (ESC)"
                >
                  <div className="absolute inset-0 bg-gradient-to-br from-slate-500/5 opacity-0 transition-opacity duration-300 group-hover:opacity-100"></div>
                  <span className="relative text-xl">✕</span>
                </button>
              </div>
            </div>

            {/* Content area */}
            <div className="overflow-auto">{renderContent()}</div>
          </div>
        </div>
      </div>
    </>
  )
}
